name: update_birthday

on:
  workflow_run:
    workflows: ["btest_birthday"]
    types: [completed]


jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          mask-aws-account-id: true

      - name: Archive directory to zip file
        run: sudo zip -r src.zip . -x .git/\* .github/\*

      - name: Push to S3
        run: aws s3 cp ./src.zip s3://${{ secrets.S3_BUCKET_NAME }}/src.zip
        
      - name: Update Lambda function code
        # run: aws lambda update-function-code --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} --zip-file fileb://src.zip
        run: aws lambda update-function-code --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} --s3-bucket ${{ secrets.S3_BUCKET_NAME }} --s3-key src.zip
